development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:10eac4d543b9e3c1d13c703acee0fd53@crestfish.redistogo.com:10130/
  channel_prefix: Eris_production
